### PR TITLE
handle input areas, too

### PR DESCRIPTION
**Pull request by lmamane**

### CODE REVIEW

**Comment by docwhat** [comment]
See #35 for some of the issues with this.

**Comment by docwhat** [comment]
Also, you can't do this for all input elements. Only text. Changing the text in an input is different than a textarea so you'll have to special case a lot of cacheobj code.

**Comment by lmamane** [comment]
I originally indeed thought I should do it only for input _text_ elements. But then, I tried clicking on the "edit" button in e.g. a boolean input, and it works! I'll admit utility may be dubious, though.

OK not to change the version.

Issue #35 seems to discuss in detail HTML5 contenteditable sections, but about input elements only "more than just changing a couple of lines of code".

**Comment by lmamane** [comment]
codacy/pr complains that I use a variable name that was already defined (!) and that I follow the same quoting style already used. I'm thus going to ignore it.

**Pull request closed without merging**
